export const WORKSHOPS = [
  {
    id: "purrfect-space-2026-07-25",
    name: "Flower Arranging Workshop",
    place: "Purrfect Space",
    address: "11, Imperial Arcade, Brighton and Hove, Brighton BN1 3EA",
    date: "25 July 2026",
    time: "1pm",
    duration: "120 mins",
    price: 35,
    description: "Spend a relaxing afternoon in Brighton creating a beautiful pet-safe bouquet surrounded by playful cats. This longer session gives you plenty of time to craft something special while enjoying a free drink and feline company. All levels welcome.",
    included: ["Your bouquet to take home", "Free Drink", "Cat play time"],
    accent: "#C4A2B0",
    image: "https://lh3.googleusercontent.com/d/1VwBn0d7xmKWaOJrVE9HSQsKF08CPOynK",
    bookingType: "external",
    bookingUrl: "https://ecom.roller.app/purrfectspace/artworkshop/en/product/1315239?date=2026-07-25",
    status: "live",
  },
  {
    id: "kings-dog-daycare-monthly",
    name: "Flower Arranging Workshop",
    place: "King's Dog Daycare",
    address: "177 Fulham Road, Chelsea, London SW3 6JW",
    date: "Monthly",
    time: "1pm",
    duration: "60-90 mins",
    price: 35,
    description: "Relax with dogs and enjoy a creative afternoon of flower arranging. Whether you're a complete beginner or just looking for something different, this laid-back workshop is for you. Bring your furry friend along and make something beautiful together. All levels welcome - come meet like-minded people and leave with a gorgeous bouquet.",
    upcomingDates: [
      { date: "01 August 2026", day: "Friday", time: "1pm" },
      { date: "01 August 2026", day: "Friday", time: "3:30pm" },
    ],
    included: ["Your bouquet to take home", "Free Drink", "Dog Treat"],
    accent: "#B8926A",
    image: "https://lh3.googleusercontent.com/d/1DHMIRqEqKT82vywOf77C5C_l4Ayj_UNT=w800",
    bookingType: "external",
    bookingUrl: "https://kingsdogdaycare.replit.app/events",
    status: "live",
  },
  {
    id: "paws-cat-cafe-2026-06-26",
    name: "Flower Arranging Workshop",
    place: "Alfi Spitalfields Market",
    address: "3 Crispin Place, London E1 6DW",
    date: "Monthly",
    upcomingDates: [
      { date: "14 August 2026", day: "Friday", time: "18:30pm" },
      { date: "11 September 2026", day: "Friday", time: "18:30pm" },
      { date: "9 October 2026", day: "Friday", time: "18:30pm" },
      { date: "13 November 2026", day: "Friday", time: "18:30pm" },
    ],
    time: "18:30pm",
    duration: "60 mins",
    price: 48,
    description: "Spend a relaxed evening at Alfi creating your own seasonal floral arrangement in a stylish Italian setting. Enjoy a complimentary drink, unwind with friends, and let your creativity bloom. Perfect for beginners and experienced flower lovers alike.",
    included: ["Your bouquet to take home", "Glass of prosecco"],
    accent: "#8DA399",
    image: "https://lh3.googleusercontent.com/d/1EkWGa7V1JU7xAbQDpFigeJp54T_JO3qF=w800",
    bookingType: "external",
    bookingUrl: "https://www.alfi.ltd/sip-and-bouquet-london#sip-bouquet-tickets",
    status: "live",
  },
];

export const upcomingWorkshops = () => WORKSHOPS.filter((w) => w.status !== "past");
export const redeemableWorkshops = () => WORKSHOPS.filter((w) => w.status !== "past");
