export const WORKSHOPS = [
  {
    id: "kings-dog-daycare-2026-05-30",
    name: "Flower Arranging Workshop",
    place: "King's Dog Daycare",
    address: "117 Fulham Road, London, SW3 6JW",
    date: "30 May 2026",
    time: "1pm",
    duration: "60-90 mins",
    price: 35,
    description: "Relax with dogs and enjoy a creative afternoon of flower arranging. Whether you're a complete beginner or just looking for something different, this laid-back workshop is for you. Bring your furry friend along and make something beautiful together. All levels welcome - come meet like-minded people and leave with a gorgeous bouquet.",
    included: ["Your bouquet to take home", "x1 drink included", "Doggy treat cup if you bring a furry friend"],
    accent: "#B8926A",
    image: "https://lh3.googleusercontent.com/d/1CAoxohkarGmRVzsdAaUSSr7HG2VMWH4O=w800",
    bookingType: "external",
    bookingUrl: "https://kingsdogdaycare.replit.app/events/1",
    status: "past",
  },
  {
    id: "cat-titude-2026-06-19",
    name: "Flower Arranging Workshop",
    place: "Cat-titude Cat Cafe",
    address: "134 St John's Hill, London, SW11 1SL",
    date: "19 June 2026",
    time: "6pm",
    duration: "60-90 mins",
    price: 35,
    description: "Enjoy a creative evening surrounded by cats at the cosiest cafe in town. Unwind after work, learn to arrange a beautiful pet-safe bouquet, and soak up the calm vibes. All levels welcome - no experience needed, just come ready to relax and meet like-minded people.",
    included: ["Your bouquet to take home", "Prosecco (+£10 add-on)", "Cat play time"],
    accent: "#C4A2B0",
    image: "https://lh3.googleusercontent.com/d/1YxXERg81kUe5wSQdxoncSSYFMKaBSaE9=w800",
    bookingType: "external",
    bookingUrl: "https://bookwhen.com/cat-titudecatcafe/e/ev-s3tgt-20260619180000",
    status: "live",
  },
  {
    id: "paws-cat-cafe-2026-06-26",
    name: "Flower Arranging Workshop",
    place: "Paws Cat Café",
    address: "Angel Walk, 5 Angel Lane, Tonbridge, TN9 1TJ",
    date: "26 June 2026",
    time: "6pm",
    duration: "60-90 mins",
    price: 45,
    description: "Spend a relaxed evening at Paws Cat Café arranging your own pet-safe bouquet while playing with the resident cats. Sip on a complimentary drink and let your creativity flow in this charming, calming setting. All levels welcome.",
    included: ["Your bouquet to take home", "Free drink included", "Cat play time"],
    accent: "#8DA399",
    image: "https://lh3.googleusercontent.com/d/1vyvkDLBp9j2-dxnL7AyAfBXbYlKKuk4a=w800",
    bookingType: "external",
    bookingUrl: "https://pawscatcafe.resova.co.uk/items/view/37",
    status: "live",
  },
];

export const upcomingWorkshops = () => WORKSHOPS.filter((w) => w.status !== "past");
export const pastWorkshops = () => WORKSHOPS.filter((w) => w.status === "past");
export const redeemableWorkshops = () => WORKSHOPS.filter((w) => w.status !== "past");
